<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>ChessController.Tests</RootNamespace>
        <EnableMicrosoftTestingPlatformExtensions>true</EnableMicrosoftTestingPlatformExtensions>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.0" />
        <PackageReference Include="coverlet.MTP" Version="1.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Pieces\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ChessController\ChessController.csproj" />
    </ItemGroup>

</Project>
